<?php

use Faker\Generator as Faker;

$factory->define(App\Models\Request::class, function (Faker $faker) {
    return [
        'date' => date('Y-m-d'),
        'type' => rand(1, 2),
        'level' => 'cendi',
        'name' => $faker->name,
        'last_name' => $faker->lastName,
        'mat_last_name' => $faker->lastName,
        'curp' => $faker->text(18),
        'grade' => $faker->numberBetween(1, 6) . 'A',
        'sanguine' => 'O+',
        'place_birth' => $faker->city,
        'birthday' => $faker->date(),
        'age' => $faker->numberBetween(6, 16),
        'street' => $faker->streetName,
        'number' => $faker->numberBetween(1, 500),
        'colony' => $faker->city,
        'town' => $faker->city,
        'zip_code' => $faker->numberBetween(00000, 99999),
        'origin_school' => $faker->name,
        'f_name' => $faker->name,
        'f_last_name' => $faker->lastName,
        'f_mat_last_name' => $faker->lastName,
        'f_company' => $faker->company,
        'f_position' => $faker->text(10),
        'f_office_phone' => $faker->numberBetween(1111111, 9999999),
        'f_home_phone' => $faker->numberBetween(1111111, 9999999),
        'f_cellphone' => $faker->numberBetween(1111111, 9999999),
        'f_email' => $faker->email,
        'm_name' => $faker->name,
        'm_last_name' => $faker->lastName,
        'm_mat_last_name' => $faker->lastName,
        'm_company' => $faker->company,
        'm_position' => $faker->text(10),
        'm_office_phone' => $faker->numberBetween(1111111, 9999999),
        'm_home_phone' => $faker->numberBetween(1111111, 9999999),
        'm_cellphone' => $faker->numberBetween(1111111, 9999999),
        'm_email' => $faker->email,
        'o_name' => $faker->name,
        'o_last_name' => $faker->lastName,
        'o_mat_last_name' => $faker->lastName,
        'relationship' => $faker->text(10),
        'o_office_phone' => $faker->numberBetween(1111111, 9999999),
        'o_home_phone' => $faker->numberBetween(1111111, 9999999),
        'o_cellphone' => $faker->numberBetween(1111111, 9999999),
        'o_email' => $faker->email,
        'observations' => $faker->text(255),
        'authorization' => $faker->numberBetween(1, 2)
    ];
});
