<?php

namespace Tests;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Notification;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Notification::fake();

        $this->seed('BouncerSeeder');
    }

    protected function createSuperadmin()
    {
        return tap(factory(User::class)->create(), function ($user) {
            $user->assign('superadmin');
        });
    }

    protected function createAdmin()
    {
        return tap(factory(User::class)->create(), function ($user) {
            $user->assign('admin');
        });
    }

    protected function createUser(array $attributes = [])
    {
        return tap(factory(User::class)->create(), function ($user) {
            $user->assign('user');
        });
    }
}
